global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "hadilao-api"
    metrics_path: "/api/v1/metrics"
    static_configs:
      # Windows baseline: scrape app on host from Docker
      - targets: ["host.docker.internal:3001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]